import {DarkTheme} from '@react-navigation/native';
export const darkTheme = {
  colors: {
    ...DarkTheme.colors,

    //status bar color
    sameBarStyle: 'light-content',
    statusBarColor: 'light-content',

    //text
    textPrimary: '#FFAF30',
    textSecondary: '#E8E7EA',
    textTertiary: '#CDCCD0',
    textQuaternary: '#9998A0',
    textQuinary: '#CDCCD0',
    textSenary: '#E0DFEF',
    textSeptenary: '#9998A0',
    textOctonary: '#9998A0',
    textNonary: '#E8E7EA',
    textDenary: '#CDCCD0',
    textPrimaryVariant: '#FFAF30',
    textTertiaryVariant: '#FFAF30',
    textQuaternaryVariant: '#9998A0',
    textQuinaryVariant: '#FFAF30',
    textSecondaryVariant: '#C1BFDF',
    textSenaryVariant: '#6A6B87',
    textSeptenaryVariant: '#E8E7EA',
    textOctonaryVariant: '#E8E7EA',
    textNonaryVariant: '#FFAF30',
    textDenaryVariant: '#FFFFFF',

    //background
    bgPrimary: '#2E2446',
    bgSecondary: '#1A1721',
    bgTertiary: '#1A1721',
    bgQuaternary: '#2E293A',
    bgQuinary: '#2E2F44',
    bgOctonary: '#3F405B',
    bgSenary: '#25212F',
    bgSeptenary: '#3F405B',
    bgNonary: '#2E2F44',
    bgDenary: '#6A6B87',
    bgPrimaryVariant: '#25212F',
    bgSecondaryVariant: '#3F405B',
    bgTertiaryVariant: '#9998A0',
    bgQuaternaryVariant: '#635BFE',

    //button
    btnPrimary: '#CDCCD0',
    btnSecondary: '#1A1721',
    btnTertiary: '#FFAF30',
    btnQuaternary: '#6A6B87',
    btnQuinary: '#3F405B',
    btnOctonary: '#635BFE',
    btnSenary: '#FFFFFF',
    btnSeptenary: '#9998A0',
    btnNonary: '#9D80F8',
    btnDenary: '#635BFE',

    //interface
    ifPrimary: '#6A6B87',
    ifSecondary: '#332E40',
    ifTertiary: '#2E293A',
    ifQuaternary: '#635BFE',
    ifQuinary: '#E7E5FF',
    ifSenary: '#E0DFEF',
    ifSeptenary: '#25212F',
    ifOctonary: '#E43E66',
    ifNonary: '#5DC888',
    ifDenary: '#E8E7EA',
    ifPrimaryVariant: '#3C3747',

    //indicator
    ifIndicatorSecondary: '#3F405B',

    //border
    borderPrimary: '#3F405B',
    borderSecondary: '#332E40',
    borderTertiary: '#332E40',
    borderQuaternary: '#FFFFFF',
    borderQuinary: '#6A6B87',
    borderSenary: '#2E2446',
    borderSeptenary: '#3F405B',
    borderOctonary: '#392F6B',
    borderNonary: '#9998A0',
    borderDenary: '#3F405B',
    borderPrimaryVariant: '#332E40',

    //svg
    rightArrow: '#9998A0',
    currencyIcon: '#FFAF30',
    copyPrimary: '#CDCCD0',
    mailIcon: '#E8E7EA',
    userIcon: '#E8E7EA',
    verticalPrimary: '#9998A0',
    filePrimary: '#CDCCD0',
    tabIconUnfocused: '#9998A0',
    drawerIconUnfocused: '#C1BFDF',
    switchIcon: '#E8E7EA',
    receivedRequestIcon: '#9D80F8',

    //same value
    cornflowerBlue: '#635BFE',
    white: '#FFFFFF',
    sunshade: '#FFAF30',
    snuff: '#E0DFEF',
    mischka: '#E8E7EA',
    bastille: '#1A1721',
    gunPowder: '#3F405B',
    stormGray: '#6A6B87',
    green: '#5DC888',
    jacarta: '#392F6B',
    manatee: '#9998A0',
    whisper: '#F5F6FA',
    martinique: '#2E2446',
    lavenderGray: '#C1BFDF',
    ceriseRed: '#E43E66',
    haiti: '#0D0B2B',
  },
};
